# Lecture 6: Introduction to NumPy

<section style = "background-color: powderblue;">
<h6></h6>
<h2>Outline<span class="tocSkip"></span></h2>
<hr>
<div class="toc"><ul class="toc-item"><li><span><a href="#1.-Introduction-to-NumPy" data-toc-modified-id="1.-Introduction-to-NumPy-1">1. Introduction to NumPy</a></span></li><li><span><a href="#2.-NumPy-Arrays" data-toc-modified-id="2.-NumPy-Arrays-2">2. NumPy Arrays</a></span></li><li><span><a href="#3.-Index-and-slice" data-toc-modified-id="3.-Index-and-slice-3">3. Index and slice</a></span></li><li><span><a href="#4.-Useful-NumPy-Functions" data-toc-modified-id="4.-Useful-NumPy-Functions-4">4. Useful NumPy Functions</a></span></li><li><span><a href="-Learning-Resources" data-toc-modified-id="Learning-Resources-5">Learning Resources</a></span></li></ul></div>
<h6></h6>   
</section>

## Learning Objectives
<hr>

- Create arrays with built-in functions inlcuding `np.array()`, `np.arange()`, `np.linspace()` and `np.full()`, `np.zeros()`, `np.ones()`
- Access values from a NumPy array by numeric indexing and slicing and boolean indexing
- Perform mathematical operations on and with arrays.
- Reshape arrays by adding/removing/reshaping axes with `.reshape()`, `np.newaxis()`, `.ravel()`, `.flatten()`
- Understand how to use built-in NumPy functions like `np.sum()`, `np.mean()`, `np.log()` as stand alone functions or as methods of numpy arrays.

## 1. Introduction to NumPy
<hr>

![Numpy](https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/NumPy_logo_2020.svg/1200px-NumPy_logo_2020.svg.png)

NumPy stands for "Numerical Python" and is a popular Python library that provides support for large, multi-dimensional arrays and matrices, as well as a large collection of mathematical functions to operate on these arrays. NumPy is widely used in the scientific computing community, including fields such as data science, machine learning, physics, and engineering. In this lecture, we will cover the basics of NumPy, including array creation, indexing, slicing, and basic operations.

### 1.1 Python Libraries

In Python, a library is a collection of pre-written code that can be used to perform various tasks. Libraries are designed to make programming tasks easier by providing a set of functions and tools that can be used by programmers to perform specific tasks without having to write the code from scratch.

In [1]:
# a simple example of how to use the random Python library to generate a random number
import random

# Generate a random number between 1 and 10
random_number = random.randint(1, 10)

# Print the random number
print(random_number)


8


To install a Python library, you can use a package manager such as pip. Pip is a command-line tool that comes pre-installed with Python, and it allows you to easily install and manage Python packages and libraries.

1. Open a command-line interface (such as Terminal on Mac/Linux or Command Prompt on Windows).



2. Use the following command to install the library:

In [ ]:
# pip install library-name
pip install numpy


3. Press enter and pip will download and install the library and its dependencies. This may take a few seconds to several minutes depending on the size of the library and your internet connection.

4. Once the library is installed, you can import it into your Python code using the import statement. 

In [3]:
import random

# Use the random library in your code


>Alternatively, you can install Python libraries using a GUI tool such as Anaconda Navigator or PyCharm. These tools provide a user-friendly interface for managing packages and libraries, and they may be more convenient for beginners or for managing larger projects with multiple dependencies.

Python has a large and active community of developers who have created many useful libraries for a wide range of applications. Some popular Python libraries include <u>NumPy, Pandas, Matplotlib, SciPy, TensorFlow, PyTorch, Scikit-learn, and Django</u>, among others. These libraries can greatly simplify the process of writing complex programs, and they can save developers a lot of time and effort.

### 1.2 Install Numpy

#### 1.2.1 With the Command Prompt

    (1) First, type Command Prompt in the Windows search box.

    (2) Next, open the Command Prompt, and you’ll see the following screen with your user name (to avoid any permission issues, you may consider to run the Command Prompt as an administrator).
    
    (3) In the Command Prompt, type “cd\” as this command will ensure that your starting point has only the drive name.
    
    (4) Press Enter. Now you’ll see the drive name of C:\>.
    
    (5) Locate your Python Scripts path. The Scripts folder can be found within the Python application folder, where you originally installed Python.
    
        Here is an example of a Python Scripts path:

        C:\Users\You\AppData\Local\Programs\Python\Python39\Scripts
    
    (6) In the Command Prompt, type cd followed by your Python Scripts path.
    
        C:\>cd C:\Users\You\AppData\Local\Programs\Python\Python39\Scripts
    
    (7) Press Enter, and you’ll see something similar to the following.
    
        C:\Users\You\AppData\Local\Programs\Python\Python39\Scripts>
        
     (8) Now, type the pip install command to install your Python package. The pip install command has the following structure:
    

In [ ]:
pip install numpy

        C:\Users\You\AppData\Local\Programs\Python\Python39\Scripts>pip install pandas

      (9) Finally, press Enter, and you’ll notice that the package (here it’s pandas) will be installed:
      
         Successfully installed numpy 

#### 1.2.2 With Anaconda

Pandas can be installed using `conda`:

```
conda install pandas
```

![conda install](https://docs.conda.io/projects/conda/en/latest/_images/installing-with-conda.png)

NumPy can be installed using `conda` (if not already):

```
conda install numpy

```

More details [here.](https://docs.conda.io/projects/conda/en/latest/user-guide/concepts/installing-with-conda.html)

## 2. NumPy Arrays
<hr>

### 2.1 What are Arrays?

In computer programming, an array is a data structure that stores a collection of elements, where each element is of the same data type and is accessed using an index or a key. 

Arrays in Python are implemented using the built-in list data type, which can store elements of any data type. However, Python also provides a specialized library for working with arrays called NumPy (Numerical Python), which provides support for large, multi-dimensional arrays and matrices, as well as a large collection of mathematical functions to operate on these arrays.

In data analysis, arrays are used to store and manipulate data sets and perform statistical analysis on them, such as calculating means, variances, and correlations.

NumPy arrays ("ndarrays") are homogenous, which means that items in the array should be of the same type. ndarrays are also compatible with numpy's vast collection of in-built functions!

![arrays](https://i.stack.imgur.com/NWTQH.png)

Usually we import numpy with the alias `np` (to avoid having to type out n-u-m-p-y every time we want to use it):

In [4]:
import numpy as np

A numpy array is sort of like a list:

In [5]:
my_list = [1, 2, 3, 4, 5]
my_list

[1, 2, 3, 4, 5]

In [6]:
my_array = np.array([1, 2, 3, 4, 5])
my_array

array([1, 2, 3, 4, 5])

But it has the type `ndarray`:

In [7]:
type(my_array)

numpy.ndarray

Unlike a list, arrays can only hold a single type (usually numbers):

In [8]:
my_list = [1, "hi"]
my_list

[1, 'hi']

In [9]:
my_array = np.array((1, "hi"))
my_array

array(['1', 'hi'], dtype='<U11')

Above: NumPy converted the integer `1` into the string `'1'`!

In [15]:
my_arr = np.arange(10)
my_list = list(range(10))
my_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
my_list

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [17]:
print(my_arr)

[0 1 2 3 4 5 6 7 8 9]


In [18]:
#! ipython id=ee0ca0270fa84c3b8ed5addd00c8d501
%timeit my_arr2 = my_arr * 2
%timeit my_list2 = [x * 2 for x in my_list]

5.54 µs ± 671 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
3.53 µs ± 586 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


### 2.2 Create arrays

ndarrays are typically created using two main methods:
1. From existing data (usually lists or tuples) using `np.array()`, like we saw above; or,
2. Using built-in functions such as `np.arange()`, `np.linspace()`, `np.zeros()`, etc.

In [20]:
my_list = [1, 2, 3, 4, 5]
np.array(my_list)

array([1, 2, 3, 4, 5])

Just like you can have "multi-dimensional lists" (by nesting lists in lists), you can have multi-dimensional arrays (indicated by double square brackets `[[ ]]`):

In [19]:
list_2d = [[1, 2], [3, 4], [5, 6]]
list_2d

[[1, 2], [3, 4], [5, 6]]

In [9]:
array_2d = np.array(list_2d)
array_2d

array([[1, 2],
       [3, 4],
       [5, 6]])

You'll probably use the built-in numpy array creators quite often. Here are some common ones (hint - don't forget to check the docstrings for help with these functions, if you're in Jupyter, remeber the `shift + tab` shortcut):

In [21]:
np.arange(1, 5)  # from 1 inclusive to 5 exclusive

array([1, 2, 3, 4])

In [22]:
np.arange(0, 11, 2)  # step by 2 from 1 to 11

array([ 0,  2,  4,  6,  8, 10])

In [23]:
np.linspace(0, 10, 5)  # 5 equally spaced points between 0 and 10

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [24]:
np.ones((2, 2))  # an array of ones with size 2 x 2

array([[1., 1.],
       [1., 1.]])

In [25]:
np.zeros((2, 3))  # an array of zeros with size 2 x 3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [15]:
np.full((3, 3), 3.14)  # an array of the number 3.14 with size 3 x 3

array([[3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14]])

In [16]:
np.full((3, 3, 3), 3.14)  # an array of the number 3.14 with size 3 x 3 x 3

array([[[3.14, 3.14, 3.14],
        [3.14, 3.14, 3.14],
        [3.14, 3.14, 3.14]],

       [[3.14, 3.14, 3.14],
        [3.14, 3.14, 3.14],
        [3.14, 3.14, 3.14]],

       [[3.14, 3.14, 3.14],
        [3.14, 3.14, 3.14],
        [3.14, 3.14, 3.14]]])

In [26]:
np.random.rand(5, 2)  # random numbers uniformly distributed from 0 to 1 with size 5 x 2

array([[0.65770038, 0.30456044],
       [0.06229368, 0.59964411],
       [0.56833593, 0.17200863],
       [0.69155728, 0.0778229 ],
       [0.81535607, 0.46663311]])

There are many useful attributes/methods that can be called off numpy arrays:

In [27]:
print(dir(np.ndarray))

['T', '__abs__', '__add__', '__and__', '__array__', '__array_finalize__', '__array_function__', '__array_interface__', '__array_prepare__', '__array_priority__', '__array_struct__', '__array_ufunc__', '__array_wrap__', '__bool__', '__class__', '__class_getitem__', '__complex__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dir__', '__divmod__', '__dlpack__', '__dlpack_device__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__ilshift__', '__imatmul__', '__imod__', '__imul__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__irshift__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lshift__', '__lt__', '__matmul__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdivmod__', '__reduce__', '

In [28]:
x = np.random.rand(5, 2)
x

array([[0.88502147, 0.14105174],
       [0.28685039, 0.03828   ],
       [0.91982242, 0.84419175],
       [0.90339818, 0.26349215],
       [0.08397601, 0.07374593]])

In [29]:
x.transpose()

array([[0.88502147, 0.28685039, 0.91982242, 0.90339818, 0.08397601],
       [0.14105174, 0.03828   , 0.84419175, 0.26349215, 0.07374593]])

In [21]:
x.mean()

0.5086632185578763

In [30]:
x.astype(int)

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]])

### 2.3 Array Shapes

Arrays can be of any dimension, shape and size you desire. In fact, there are three main array attributes you need to know to work out the characteristics of an array:
- `.ndim`: the number of dimensions of an array
- `.shape`: the number of elements in each dimension (like calling `len()` on each dimension)
- `.size`: the total number of elements in an array (i.e., the product of `.shape`)

In [31]:
array_1d = np.ones(3)
print(f"Dimensions: {array_1d.ndim}")
print(f"     Shape: {array_1d.shape}")
print(f"      Size: {array_1d.size}")

Dimensions: 1
     Shape: (3,)
      Size: 3


Let's turn that print action into a function and try out some other arrays:

In [32]:
def print_array(x):
    print(f"Dimensions: {x.ndim}")
    print(f"     Shape: {x.shape}")
    print(f"      Size: {x.size}")
    print("")
    print(x)

In [33]:
array_2d = np.ones((3, 2))
print_array(array_2d)

Dimensions: 2
     Shape: (3, 2)
      Size: 6

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [34]:
array_4d = np.ones((1, 2, 3, 4))
print_array(array_4d)

Dimensions: 4
     Shape: (1, 2, 3, 4)
      Size: 24

[[[[1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]]

  [[1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]]]]


After 3 dimensions, printing arrays starts getting pretty messy. As you can see above, the number of square brackets (`[ ]`) in the printed output indicate how many dimensions there are: for example, above, the output starts with 4 square brackets `[[[[` indicative of a 4D array.

### 2.4 Reshaping Arrays

We introduce 3 key reshaping methods for reshaping numpy arrays here:
- `.rehshape()`
- `np.newaxis`
- `.ravel()`/`.flatten()`

In [35]:
x = np.full((4, 3), 3.14)
x

array([[3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14]])

You'll reshape arrays farily often and the `.reshape()` method is pretty intuitive:

In [36]:
x.reshape(6, 2)

array([[3.14, 3.14],
       [3.14, 3.14],
       [3.14, 3.14],
       [3.14, 3.14],
       [3.14, 3.14],
       [3.14, 3.14]])

In [37]:
x.reshape(2, -1)  # using -1 will calculate the dimension for you (if possible)

array([[3.14, 3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14, 3.14]])

In [38]:
a = np.ones(3)
print_array(a)
b = np.ones((3, 2))
print_array(b)

Dimensions: 1
     Shape: (3,)
      Size: 3

[1. 1. 1.]
Dimensions: 2
     Shape: (3, 2)
      Size: 6

[[1. 1.]
 [1. 1.]
 [1. 1.]]


If we want to add these two arrays, we won't be able to because their dimensions are not compatible:

In [39]:
a + b

ValueError: operands could not be broadcast together with shapes (3,) (3,2) 

Sometimes you'll want to add dimensions to an array for broadcasting purposes like this. We can do that with `np.newaxis` (note that `None` is an alias for `np.newaxis`). We can add a dimension to `a` to make the arrays compatible:

In [40]:
print_array(a[:, np.newaxis])  # same as a[:, None]

Dimensions: 2
     Shape: (3, 1)
      Size: 3

[[1.]
 [1.]
 [1.]]


In [41]:
a[:, np.newaxis] + b

array([[2., 2.],
       [2., 2.],
       [2., 2.]])

Finally, sometimes you'll want to "flatten" arrays to a single dimension using `.ravel()` or `.flatten()`. `.flatten()` used to return a copy and `.ravel()` a view/reference but now they both return a copy so I can't think of an important reason to use one over the other 🤷‍♂️

In [42]:
x

array([[3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14]])

In [43]:
print_array(x.flatten())

Dimensions: 1
     Shape: (12,)
      Size: 12

[3.14 3.14 3.14 3.14 3.14 3.14 3.14 3.14 3.14 3.14 3.14 3.14]


In [44]:
print_array(x.ravel())

Dimensions: 1
     Shape: (12,)
      Size: 12

[3.14 3.14 3.14 3.14 3.14 3.14 3.14 3.14 3.14 3.14 3.14 3.14]


### 2.5 Array Data Type

All ndarrays are homogeneous, meaning that every element has the exact same data-type (e.g., integer, float, string, etc) which takes up the exact same amount of memory.

For example, consider the following 1d-array which is full of 8-bit integers (`int8`):

In [89]:
a = np.array([1, 2, 3, 4, 5, 6], dtype='int8')
a

array([1, 2, 3, 4, 5, 6], dtype=int8)

One byte is equal to eight bits ([refresh yourself on bits and bytes here](https://web.stanford.edu/class/cs101/bits-bytes.html)), so for this array of `int8` data-types, we would expect each element to take up one byte. We can confirm using:

In [90]:
a.itemsize

1

> An aside on the difference between e.g., `int8`, `int16`, `int32`. The number here refers to the number of bits used to represent each integer. For example, `int8` is an integer represented with one byte (one byte = 8 bits). Recall that bits are the basic unit of information "0/1" used by computers. So the maximum *unsigned* number that can be held with an `int8` datatype is: 2^8 (but because Python indexes from 0, the unsigned range of `int8` is 0 to 257). If we wish to have negative numbers, we need to use one of those bits to represent the sign, and we are left with 2^7 bits to make numbers with, and so the signed range of `int8` is -128 to +127. Likewise, `int16` has an unsigned range of 0 to 65,535 (2^16), or a signed range of -32,768 to +32,767, etc. It's interesting to watch what happens if you try to use a dtype that does not support the number you wish to store:

In [91]:
np.array([126, 127, 128, 129, 130, 131, 132], dtype='int8')

array([ 126,  127, -128, -127, -126, -125, -124], dtype=int8)

>Above, notice how when we exceeded the integer 127 (the max of the `int8` signed range), NumPy automatically represents this number by counting up from the minimum of the signed range (-128). Cool! Of course, this wouldn't be a problem if we used `int16`:

In [92]:
np.array([126, 127, 128, 129, 130, 131, 132], dtype='int16')

array([126, 127, 128, 129, 130, 131, 132], dtype=int16)

Finally I'll say that technically it is possible to have mixed data-types in an array (i.e., a heterogenous array), but in this case, the array still "sees" each element as the same thing: a reference to some Python object, and the dtype would be "object".

In [93]:
a = np.array([['a', 'b', 'c'], 1, 3.14159], dtype='object')
a

array([list(['a', 'b', 'c']), 1, 3.14159], dtype=object)

Above is an ndarrays of objects, each one being a reference to some other Python object with its own data-type:

In [94]:
list(map(type, a))

[list, int, float]

## 3. Index and slice
<hr>

We can access elements of a NumPy array by indexing and slicing, just like we do with lists in Python. 

### 3.1 Numeric Indexing

#### 3.1.1 1D array

In [53]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [54]:
x[0]

0

In [45]:
x[3]

array([3.14, 3.14, 3.14])

To access a range of elements, we can use slicing:

In [55]:
x[2:]

array([2, 3, 4, 5, 6, 7, 8, 9])

In [56]:
x[:4]

array([0, 1, 2, 3])

In [57]:
x[2:5]

array([2, 3, 4])

In [58]:
x[2:3]

array([2])

In [60]:
x[5:0:-1]

array([5, 4, 3, 2, 1])

#### 3.1.2 2D arrays

In [61]:
x = np.random.randint(10, size=(4, 6))
x

array([[6, 3, 3, 2, 5, 7],
       [4, 2, 1, 7, 6, 0],
       [5, 1, 9, 7, 9, 9],
       [0, 7, 2, 2, 2, 6]])

In [62]:
x[3, 4]  

2

In [63]:
x[3][4] 

2

In [65]:
x[3]

array([0, 7, 2, 2, 2, 6])

In [66]:
len(x)  # generally, just confusing

4

In [67]:
x.shape

(4, 6)

In [68]:
x[:, 2]  # column number 2

array([3, 1, 9, 2])

In [69]:
x[2:, :3]

array([[5, 1, 9],
       [0, 7, 2]])

In [70]:
x.T

array([[6, 4, 5, 0],
       [3, 2, 1, 7],
       [3, 1, 9, 2],
       [2, 7, 7, 2],
       [5, 6, 9, 2],
       [7, 0, 9, 6]])

In [71]:
x

array([[6, 3, 3, 2, 5, 7],
       [4, 2, 1, 7, 6, 0],
       [5, 1, 9, 7, 9, 9],
       [0, 7, 2, 2, 2, 6]])

In [72]:
x[1, 1] = 555555
x

array([[     6,      3,      3,      2,      5,      7],
       [     4, 555555,      1,      7,      6,      0],
       [     5,      1,      9,      7,      9,      9],
       [     0,      7,      2,      2,      2,      6]])

In [73]:
z = np.zeros(5)
z

array([0., 0., 0., 0., 0.])

In [96]:
z[0] = 5
z

array([5., 0., 0., 0., 0.])

### 3.2 Boolean Index

In [74]:
x = np.random.rand(10)
x

array([0.47462688, 0.94389358, 0.09066656, 0.15345039, 0.30142955,
       0.34514962, 0.49864012, 0.91980773, 0.02223219, 0.17696289])

In [75]:
x + 1

array([1.47462688, 1.94389358, 1.09066656, 1.15345039, 1.30142955,
       1.34514962, 1.49864012, 1.91980773, 1.02223219, 1.17696289])

In [76]:
x_thresh = x > 0.5
x_thresh

array([False,  True, False, False, False, False, False,  True, False,
       False])

In [77]:
x[x_thresh] = 0.5  # set all elements  > 0.5 to be equal to 0.5
x

array([0.47462688, 0.5       , 0.09066656, 0.15345039, 0.30142955,
       0.34514962, 0.49864012, 0.5       , 0.02223219, 0.17696289])

In [78]:
x = np.random.rand(10)
x

array([0.98242323, 0.26076361, 0.21107291, 0.89081724, 0.51093956,
       0.99183734, 0.04131897, 0.73106143, 0.77004137, 0.28401792])

In [79]:
x[x > 0.5] = 0.5
x

array([0.5       , 0.26076361, 0.21107291, 0.5       , 0.5       ,
       0.5       , 0.04131897, 0.5       , 0.5       , 0.28401792])

## 4. Useful NumPy Functions

NumPy provides several functions to perform basic mathematical operations on arrays, such as addition, subtraction, multiplication, and division. These operations are performed element-wise, which means the corresponding elements of two arrays are combined to produce a new array.

In [80]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr3 = arr1 + arr2
print(arr3)

[5 7 9]


In [81]:
arr1 = np.array([1, 2, 3])
arr2 = arr1 * 2
print(arr2)

[2 4 6]


NumPy also provides several functions to perform mathematical operations on arrays, such as mean(), max(), min(), and std().

In [82]:
arr = np.array([1, 2, 3, 4, 5])
mean_value = np.mean(arr)
print(mean_value)

3.0


In [83]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
sum_value = np.sum(arr)
print(sum_value)

21


In [84]:
sides = np.array([3, 4])

There are several ways we could solve this problem. We could directly use Pythagoras's Theorem:

$$c = \sqrt{a^2+b^2}$$

In [85]:
np.sqrt(np.sum([np.power(sides[0], 2), np.power(sides[1], 2)]))

5.0

We can leverage the fact that we're dealing with a numpy array and apply a "vectorized" operation (more on that in a bit) to the whole vector at one time:

In [86]:
(sides ** 2).sum() ** 0.5

5.0

Or we can simply use a numpy built-in function (if it exists):

In [87]:
np.linalg.norm(sides)  

5.0

In [88]:
np.hypot(*sides)

5.0

## Summary

In this lecture, we covered the basics of NumPy, including array creation, indexing, slicing, and basic operations. NumPy is a powerful library that provides support for large, multi-dimensional arrays and matrices, as well as a large collection of mathematical functions to operate on these arrays. NumPy is widely used in the scientific computing community and is an essential tool for data science, machine learning, physics, and engineering. In the next chapter, we will cover more advanced topics in NumPy, including broadcasting, array manipulation, and linear algebra operations.

## Learning Resources

- NumPy official documentation: https://numpy.org/doc/stable/

- NumPy tutorial on W3Schools: https://www.w3schools.com/python/numpy_intro.asp

- NumPy tutorial on DataCamp: https://www.datacamp.com/community/tutorials/python-numpy-tutorial

- NumPy tutorial on Real Python: https://realpython.com/numpy-tutorial/

- NumPy tutorial on TutorialsPoint: https://www.tutorialspoint.com/numpy/index.htm